version: "3.3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181"
    networks:
      - ilhammhdd-docker-net
    volumes:
      - type: volume
        source: ilhammhdd-zookeeper-data-volume
        target: /opt/zookeeper-3.4.9/data
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "192.168.99.100"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: volume
        source: ilhammhdd-kafka-volume
        target: /kafka
    networks:
      - ilhammhdd-docker-net

networks:
  ilhammhdd-docker-net:
    external:
      name: ilhammhdd-docker-net
      
volumes:
  ilhammhdd-kafka-volume:
    external:
      name: ilhammhdd-kafka-volume
  ilhammhdd-zookeeper-data-volume:
    external:
      name: ilhammhdd-zookeeper-data-volume