version: "3"

services:
  kudaki_zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: kudaki_zookeeper
    hostname: kudaki_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 3000
    ports:
      - "2181:2181"
    restart: always
    networks:
      - kudaki-docker-net
  
  kudaki_kafka:
    image: confluentinc/cp-kafka
    container_name: kudaki_kafka
    hostname: kudaki_kafka
    depends_on:
      - kudaki_zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: kudaki_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kudaki_kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "29092:29092"
      - "9092:9092"
    restart: always
    networks:
      - kudaki-docker-net

networks:
  kudaki-docker-net:
    external: true