version: "3.3"

services:

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    ports:
      - "2181:2181"
    networks:
      - ilhammhdd-docker-net
    restart: always

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "192.168.99.100"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: "USER:5:1,SHOP:5:1,MOUNTAIN:5:1,ITEM:5:1,REVIEW:5:1,EVENT:5:1,RENT:5:1,COMMAND:5:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka-data:/kafka
    networks:
      - ilhammhdd-docker-net
    restart: always

networks:
  ilhammhdd-docker-net:
    external: true
