version: "3.3"

services:

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    ports:
      - "2181:2181"
    networks:
      - ilhammhdd-docker-net
    restart: always

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "192.168.99.100"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
      KAFKA_CREATE_TOPICS: "Item:1:1,Shop:1:1,Mountain:1:1,File:1:1,Event:1:1,User:1:1,Review:1:1,Rent:1:1,EventSourceList:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka-data:/kafka
    networks:
      - ilhammhdd-docker-net
    restart: always

networks:
  ilhammhdd-docker-net:
    external: true
