version: "3.3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    networks:
      - ilhammhdd-docker-net
    restart: on-failure
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "192.168.99.100"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
      KAFKA_CREATE_TOPICS: "item:1:1,shop:1:1,mountain:1:1,file:1:1,event:1:1,user:1:1,review:1:1,rent:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: volume
        source: ilhammhdd-kafka-volume
        target: /kafka
    networks:
      - ilhammhdd-docker-net
    restart: on-failure

networks:
  ilhammhdd-docker-net:
    external:
      name: ilhammhdd-docker-net
      
volumes:
  ilhammhdd-kafka-volume:
    external: true