version: "3.3"

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    ports:
      - "2181:2181"
    restart: always
    networks:
      - kudaki-docker-net
  
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: "178.62.107.160"
      KAFKA_ZOOKEEPER_CONNET: zookeeper:2181
      KAFKA_CREATE_TOPICS: "USER:1:1,MOUNTAIN:1:1,RENTAL:1:1,EVENT:1:1"
    ports:
      - "9092:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka-data:/data
    restart: always
    networks:
      - kudaki-docker-net

networks:
  kudaki-docker-net:
    external: true