version: "3.3"

services:
  kudaki_mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    hostname: kudaki_mysql
    container_name: kudaki_mysql
    environment:
      MYSQL_ROOT_PASSWORD : mysqlrocks
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - kudaki-docker-net
    restart: always

networks:
  kudaki-docker-net:
    external: true