version: "3.3"
services:
  db-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    hostname: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD : mysqlrocks
    container_name: db-mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - ilhammhdd-docker-net
    restart: always

networks:
  ilhammhdd-docker-net:
    external: true
