[[tls]]
entryPoints = ["https"]
[tls.certificate]
certFile = "/certs/gateway.kudaki.id.crt"
keyFile = "/certs/gateway.kudaki.id.key"
[[tls]]
[tls.certificate]
certFile = "/certs/entry.kudaki.id.crt"
keyFile = "/certs/entry.kudaki.id.key"
