debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"
[entryPoints.https]
address = ":443"
[entryPoints.https.tls]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "kudaki.id"
watch = true
exposedByDefault = true
swarmMode = false
network = "kudaki-docker-net"

[file]
filename = "rules.toml"
watch = true
