debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]
insecureSkipVerify = true

[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"
[entryPoints.https]
address = ":443"
[entryPoints.https.tls]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "kudaki.id"
watch = true
exposedByDefault = true
swarmMode = false
network = "kudaki-docker-net"

[acme]
email = "milham939@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
caServer = "https://acme-v02.api.letsencrypt.org/directory"
acmeLogging = true
[acme.dnsChallenge]
provider = "cloudflare"
delayBeforeCheck = 0