debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"
[entryPoints.https]
address = ":443"
[entryPoints.https.tls]

[acme]
email = "punyakami@kudaki.id"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false
[acme.dnsChallenge]
provider = "cloudflare"
delayBeforeCheck = 0

[docker]
endpoint = "unix://var/run/docker.sock"
domain = "kudaki.id"
watch = true
exposedByDefault = false
swarmMode = false
network = "kudaki-docker-net"